### PR TITLE
Enabled file logging for some builders

### PR DESCRIPTION
**Pull request by petermost**
I've enabled file logging for the 'Native_Builder' builder and the 'copy_stockfish' builder because the console output always disappeared and I was not able to get it back to look for errors.
If you know how to display past build outputs, especially from the 'Native_Builder' then these changes are of course unnecessary.

### CODE REVIEW

**Comment by peterosterlund2** [comment]
Good idea. My workaround had been to rebuild outside of eclipse using the NDK directly. Logging to a file is a better solution.
You implementation did not work with my workspace directory structure though, so I re-implemented your change instead of merging it.

**Comment by petermost** [comment]
When you use ${project_loc} then the resulting log file is dependent on which project is currently selected when the build runs! For example: When the CuckooChess project is selected in the Package Explorer then the log file will be .../DroidFish/CuckooChess/copy_stockfish.log even though the builder is in the DroidFish project.

**Comment by petermost** [comment]
Could you test with ${build_project} instead of ${project_loc}? This works for me.

**Comment by petermost** [comment]
I'm trying to understand why the original version with ${workspace_loc:/DroidFish/copy_stockfish.log} didn't work for you. Can you describe why it failed?

**Comment by peterosterlund2** [comment]
My DroidFish project is checked out in the path ~/workspace/droidfish/DroidFish. I will test using ${project_loc} instead.

**Pull request closed without merging**
