### PR TITLE
Remove in repo colorpicker and fetch it using gradle

### PR DESCRIPTION
**Pull request by ebraminio**

### CODE REVIEW

**Comment by peterosterlund2** [comment]
From were would the code be fetched if this is merged?

**Comment by ebraminio** [comment]
This line `implementation 'net.margaritov.preference.colorpicker.ColorPickerPreference:ColorPickerPreference:1.0.0'` makes it to get it from this repo https://github.com/attenzione/android-ColorPickerPreference

**Comment by peterosterlund2** [comment]
How does it know from that line to go to github and the specific github project?

**Comment by peterosterlund2** [comment]
Also, which commit would be used?

**Comment by ebraminio** [comment]
Fair point. Indicated in the README of the GitHub project, if the all users has given star was noted something weird they would said so, either we can leave this as is or use jitpack if you don't trust them, which, is understandable to me.

**Comment by peterosterlund2** [comment]
It's not specifically that I don't trust them. I just don't like the idea that they could accidentally introduce a bug which would end up in DroidFish without me even realizing that something has changed.

**Comment by ebraminio** [comment]
Ok, lets leave this as is.

There was another dependency so thought having another will not be different. Actually I have another home baked color picker [here](https://github.com/ebraminio/DroidPersianCalendar/blob/master/PersianCalendar/src/main/java/com/byagowi/persiancalendar/ui/preferences/widgetnotification/ColorPickerView.java) (single class, no dependency/layout/resource) myself that you may interesting which doesn't support alpha yet.

**Comment by peterosterlund2** [comment]
I think the AndroidSVG dependency is downloaded from here: http://repo1.maven.org/maven2/com/caverock/androidsvg-aar/1.3/

So it should use the same code regardless of what happens in the corresponding git repository. I did not find a corresponding repository directory for the color picker, but it's possible that I just don't know where to look.

Anyway, I will keep the old code in DroidFish for now.

**Comment by ebraminio** [comment]
Oh I meant to close this with my previous comment, wrong button. Understandable. Thanks

**Pull request closed without merging**
