### PR TITLE
add hashfull information

### PR DESCRIPTION
**Pull request by aprijal-psrb**
add % hashfull information in engine info.

### CODE REVIEW

**Comment by peterosterlund2** [comment]
Thanks, merged.

**Comment by aprijal-psrb** [comment]
i'm writing ECO code, how about this:
[http://chess4android.blogspot.com/2016/10/droidfish-gui-android-eco-code.html](url)

**Comment by peterosterlund2** [comment]
Sounds interesting, but I can't find the source code so I can't review it.

**Comment by aprijal-psrb** [comment]
in my android-studio branch

**Comment by aprijal-psrb** [comment]
[HERE](https://github.com/aprijal-psrb/droidfish/commit/f666cc9f04b58c850467663fa1369f70670d6ac4) for eclipse project.

**Comment by peterosterlund2** [comment]
Thanks. I like the ECO support functionality but that implementation wastes quite a bit of CPU time. I have re-implemented ECO support in a way that performs pre-processing during app build time to make the ECO lookup a lot faster when the app is running.

**Comment by aprijal-psrb** [comment]
Thanks for the implementation, i know my programming skill is bad.   :)
I'll test it.

**Comment by peterosterlund2** [comment]
I think the current pre-processing code is wrong. For example after e4 e5 Nf3 Nf6 Nxe5 d6 the classification is "Cochrane gambit". I don't think it should do that until Nxf7 has also been played.
Should be easy to fix.

**Comment by peterosterlund2** [comment]
The pre-processing has now been fixed.

**Pull request merged**
